// <auto-generated />
using System;
using LightSpeed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightSpeed.Data.Migrations
{
    [DbContext(typeof(LightSpeedDataContext))]
    [Migration("20190421194225_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1");

            modelBuilder.Entity("LightSpeed.Data.Models.Something", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Qty");

                    b.HasKey("Id");

                    b.ToTable("Somethings");
                });
#pragma warning restore 612, 618
        }
    }
}
